### ISSUE TITLE
Documentation should mention python3

### ISSUE THREAD

**Issue by hackerb9** [Canorus/commandline-mastodon#2]
However, when trying to run using the suggested "python register.py", I got error messages because my default python is python2. 

> $ python register.py 
> input your instance: fooo
> Traceback (most recent call last):
>   File "register.py", line 3, in <module>
>     instance = input('input your instance: ')
>   File "<string>", line 1, in <module>
> NameError: name 'fooo' is not defined
>

**Comment by Canorus** [comment]
Hi @hackerb9 

First of all, I'd really like to say thank you for taking your time to read my code and test it.

This project was created and was maintained mainly for my personal use and that's why a lot of UI parts has Korean Characters.

On March, however, after some thoughts I decided to use [tootstream](https://github.com/magicalraccoon/tootstream) instead of my personal work and didn't update since. Maybe there could be some updates I didn't feel need to push.. I don't know.

In addition, I didn't have much time to maintain my codes lately. So I'm not sure when or whether I can update this repo but I promise I'll do my best to resolve the issues you presented. (Maybe I can add to README about python3 and the fact that this project is no longer maintained anymore)

Again thank you for your time and effort to raise these issues to my attention.
